/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // This name MUST match your docusaurus.config.js "sidebarId"
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
